// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_KR2KSMAmJvKfKmynm2-OD6RVjZkPao',
    appId: '1:688940067190:web:a426585cd0d5c6f2d8b257',
    messagingSenderId: '688940067190',
    projectId: 'news-1dee4',
    authDomain: 'news-1dee4.firebaseapp.com',
    storageBucket: 'news-1dee4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmuB2yrnLmSqCNKPOnRQQn3E5i2FcJ5yc',
    appId: '1:688940067190:android:683861343d1b03e3d8b257',
    messagingSenderId: '688940067190',
    projectId: 'news-1dee4',
    storageBucket: 'news-1dee4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr_KR2KSMAmJvKfKmynm2-OD6RVjZkPao',
    appId: '1:688940067190:web:af237dca76c926ebd8b257',
    messagingSenderId: '688940067190',
    projectId: 'news-1dee4',
    authDomain: 'news-1dee4.firebaseapp.com',
    storageBucket: 'news-1dee4.firebasestorage.app',
  );
}
